include:
  - project: 'Bigouden/gitlab-ci-templates'
    file: '.gitlab-ci-docker.yml'

.standalone:
  image:
    name: $CONTAINER_TEST_IMAGE
    entrypoint: [""]
  variables:
    GIT_STRATEGY: none
  dependencies: []  

variables:
  HADOLINT_ALLOW_FAILURE: "true"
  PROMETHEUS_EXPORTER_PORT: "8182"
  PROMETHEUS_EXPORTER_COMMAND: ["manage"]
    
stages:
  - Quality
  - Security
  - Build
  - Commands
  - Inspect
  - Release
  - Clean

Rclone:
  stage: Commands
  extends: .standalone
  script:
    - rclone version

Restic: 
  stage: Commands
  extends: .standalone
  script:
    - restic version

Bivac: 
  stage: Commands
  extends: .standalone
  script:
    - bivac
